### ISSUE TITLE
Links to previous year's workshop returns a 404 error

### ISSUE THREAD

**Issue by shaido987** [Graph-Learning-Benchmarks/Graph-Learning-Benchmarks.github.io#1]
Hello,

the pdf links to the accepted papers of the previous year's workshop are not working and a 404 error is returned.   
See all links here: https://graph-learning-benchmarks.github.io/glb2021/#accepted-papers.

In the links, there is an additional `/glb2021/` included, e.g., the link on the webpage is:

https://graph-learning-benchmarks.github.io/glb2021/assets/papers/EvalNE.pdf

while this works and will return the pdf:

https://graph-learning-benchmarks.github.io/assets/papers/EvalNE.pdf

**Comment by jiong-zhu** [comment]
Thank you for bringing up that issue to us! I have updated and fixed the link schemes, and the [PDF links on the webpage](https://graph-learning-benchmarks.github.io/glb2021/#accepted-papers) should now work properly. Note that older links (like the ones you posted in the comment above) will no longer work on the updated link schemes.

**Comment by shaido987** [comment]
Thanks for the quick fix, it looks to be working correctly now.
